name: deephit-torch
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - ca-certificates=2024.7.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - idna=3.7
  - joblib=1.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.0.3
  - pip=24.2
  - platformdirs=3.10.0
  - pooch=1.7.0
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - urllib3=2.2.2
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - autograd==1.7.0
    - autograd-gamma==0.5.0
    - cachetools==5.5.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - flatbuffers==24.3.25
    - fonttools==4.53.1
    - formulaic==1.0.2
    - h5py==3.11.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - interface-meta==1.3.0
    - kiwisolver==1.4.7
    - lifelines==0.27.8
    - markdown==3.7
    - matplotlib==3.7.5
    - opt-einsum==3.3.0
    - pillow==10.4.0
    - protobuf==4.25.4
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pyparsing==3.1.4
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - termcolor==2.4.0
    - typing-extensions==4.5.0
    - werkzeug==3.0.4
    - wrapt==1.16.0
    - zipp==3.20.2
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - tensorboard==2.13.0  # Tensorboard can still be useful for visualizing training
    - tqdm==4.66.1         # For progress bars
    - pandas==2.0.3        # Data analysis tools